# Generated by Django 3.2.6 on 2021-08-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
